import AboutComponent from "@/components/AboutComponent";
import CategoryComponent from "@/components/CategoryComponent";
import DiscountComponent from "@/components/DiscountComponent";
import FeatureComponent from "@/components/FeatureComponent";
import FeatureRightComponent from "@/components/FeatureRightComponent";
import { HeroComponent } from "@/components/HeroComponent";
import ProductHotComponent from "@/components/ProductHotComponent";
import ReviewComponent from "@/components/ReviewComponent";
import ShopComponent from "@/components/ShopComponent";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nika Coffee and Tea</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <HeroComponent />
        {/* <DiscountComponent /> */}
        {/* <CategoryComponent /> */}
        {/* <AboutComponent /> */}
        <FeatureComponent />
        <FeatureRightComponent />
        <FeatureComponent />
        {/* <ShopComponent /> */}
        <ProductHotComponent />
        {/* <ReviewComponent /> */}
      </main>
    </>
  );
}
