"use client"
import FeatureComponent from "@/components/FeatureComponent";
import { HeroComponent } from "@/components/HeroComponent";
import ProductHotComponent from "@/components/ProductHotComponent";
import { dataFeature } from "@/data"
import Head from "next/head";
import { useState } from "react";


export default function Home() {
  const [data, setData] = useState(dataFeature)
  return (
    <>
      <Head>
        <title>Nika Coffee and Tea</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <HeroComponent />
        {
          data.map((item) => (<FeatureComponent key={item.id} feature={item} />))
        }
        <ProductHotComponent />
      </main>
    </>
  );
}
